name: collect trending tweets daily

    
jobs:
  collect-data-job:
    name: Fetch New Tweets
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository.
        uses: actions/checkout@v2

      - name: Setup Python 3.7.
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' 

      - name: Install dependencies and run script.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python scrape.py

      - name: Commit data to repo.
        run: |
          git config --global user.email "kadamrahulj0909@gmail.com"
          git config --global user.name "Rahul kadam"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
